import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await p.goto("http://127.0.0.1:4399/ai-arai-dee/", { waitUntil: "networkidle" });
await p.waitForTimeout(1500);
await p.locator("[data-section=chapter-content]").scrollIntoViewIfNeeded();
await p.evaluate(() => window.scrollBy(0, -80));
await p.waitForTimeout(1500);
const ch1 = await p.locator("[data-section=chapter-content]").boundingBox();
if (ch1) await p.screenshot({ path: "shot-after-home.png", clip: { x: 0, y: Math.max(0, ch1.y - 40), width: 1440, height: Math.min(880, ch1.height + 60) } });
await p.goto("http://127.0.0.1:4399/ai-arai-dee/lesson/slides/", { waitUntil: "networkidle" });
await p.waitForTimeout(1200);
const hd = await p.locator("header").first().boundingBox();
if (hd) await p.screenshot({ path: "shot-after-lesson.png", clip: { x: 0, y: 0, width: 1440, height: Math.min(640, hd.y + hd.height + 60) } });
await b.close();
console.log("shots done");
